name: build

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 10

      - run: npm install
      - run: npm run build

      - name: docker-login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: docker-release
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: zwischenspiell/docker-h5ai:latest
